### ISSUE TITLE
Technically, license cannot be GPL-2

### ISSUE THREAD

**Issue by seandavi** [jamesdalg/HiCNV#2]
Since this work was performed while you were a government employee (I think), you cannot claim copyright. See appendix B for suggestions. https://nciphub.org/resources/899/download/Guidelines_for_Releasing_Research_Software_04062015.pdf

That said, this document was written after I had already produced quite a bit of open source code, so I have multiple packages that carry standard open source licenses.

**Comment by jamesdalg** [comment]
I assumed it was fine as GEOquery uses the same license. How do we reference that different type of license specified on the last page? Will CRAN accept a license designation other than the ones listed here? https://www.r-project.org/Licenses/ (pasted below)

_The following licenses are in use for R or associated software such as packages.

The “GNU Affero General Public License” version 3
The “Artistic License” version 2.0
The “BSD 2-clause License”
The “BSD 3-clause License”
The “GNU General Public License” version 2
The “GNU General Public License” version 3
The “GNU Library General Public License” version 2
The “GNU Lesser General Public License” version 2.1
The “GNU Lesser General Public License” version 3
The “MIT License”
The “Creative Commons Attribution-ShareAlike International License” version 4.0
R as a package is licensed under GPL-2 | GPL-3. File doc/COPYING is the same as GPL-2.

Some files are licensed under ‘GPL (version 2 or later)’, which includes GPL-3. See the comments in the files to see if this applies.

Some header files are distributed under LGPL-2.1: see file COPYRIGHTS (on the SVN server)._


The Plotly package itself uses MIT, which seems to grant copyright protection and ownership to plotly. https://cran.r-project.org/web/packages/plotly/index.html

Can you can show an example of a working package (on CRAN optimally, so we know it will work) that utilizes this new form of license?

**Comment by seandavi** [comment]
I don't have a good example. Yes, I cut corners with GEOquery. You might want to check with Paul and as far as what CRAN accepts, the NCI license is meant to be BSD-3 compatible. Not sure how to do that on CRAN. Feel free to ignore my comment, also. More informational than operational.

**Comment by jamesdalg** [comment]
I've changed the description for version 1.6.0 to have BSD-3 as the license type.

**Comment by jamesdalg** [comment]
I'll check with Paul in the morning, but I think this is the closest thing. I'll also ask this of the CRAN team.
